---
- name: Register docker-compose binary is installed
  ansible.builtin.stat:
    path: "{{ docker_compose_bin_directory }}/docker-compose"
  register: docker__docker_compose_bin_stat

- name: Register installed docker-compose version
  when: docker__docker_compose_bin_stat.stat.exists
  ansible.builtin.command:
    cmd: "{{ docker_compose_bin_directory }}/docker-compose version --short"
  register: docker__docker_compose_version_installed
  changed_when: false

- name: Register if docker-compose binary needs installation
  ansible.builtin.set_fact:
    docker__install_docker_compose: >-
      {{
        (not docker__docker_compose_bin_stat.stat.exists)
        or (upgrade_docker | default(false) | bool)
        or (
          (
            docker__docker_compose_version_installed.stdout
            | default('')
            | trim
          ) != docker_compose_version
        )
      }}

- name: Downloading docker-compose binary
  ansible.builtin.get_url:
    url: >-
      https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_facts['system'] | lower }}-{{ ansible_facts['architecture'] }}
    dest: "{{ docker_compose_bin_directory }}/docker-compose"
    mode: "{{ docker_compose_bin_file_perm }}"
    owner: "{{ docker_compose_bin_owner }}"
    group: "{{ docker_compose_bin_group }}"
    checksum: >-
      sha256:https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}//docker-compose-{{ ansible_facts['system'] | lower }}-{{ ansible_facts['architecture'] }}.sha256
  when: docker__install_docker_compose
