---
# Copyright (C) 2021-2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include Docker role
      include_role:
        name: githubixx.docker
