---
# Copyright (C) 2021-2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-docker-ubuntu2204
    box: alvistack/ubuntu-22.04
    memory: 1536
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
  - name: test-docker-ubuntu2004
    box: alvistack/ubuntu-20.04
    memory: 1536
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
  - name: test-docker-ubuntu2404
    box: alvistack/ubuntu-24.04
    memory: 1536
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30
  - name: test-docker-debian12
    box: generic/debian12
    memory: 1536
    cpus: 2
    groups:
      - debian
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.40
  - name: test-docker-debian11
    box: generic/debian11
    memory: 1536
    cpus: 2
    groups:
      - debian
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.50
  - name: test-docker-archlinux
    box: archlinux/archlinux
    memory: 1536
    cpus: 2
    groups:
      - archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.60

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      test-docker-archlinux:
        docker_firewall_flavor: "nftables"
      test-docker-ubuntu2204:
        docker_compose_type: "standalone"

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
