---
# Copyright (C) 2021-2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-docker-ubuntu2204
    box: generic/ubuntu2204
    memory: 1024
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10
  - name: test-docker-ubuntu2004
    box: generic/ubuntu2004
    memory: 512
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.20
  - name: test-docker-ubuntu1804
    box: generic/ubuntu1804
    memory: 512
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.30
  - name: test-docker-debian10
    box: generic/debian10
    memory: 512
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.40
  - name: test-docker-debian11
    box: generic/debian11
    memory: 512
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.50
  - name: test-docker-archlinux
    box: archlinux/archlinux
    memory: 512
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.60

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      test-docker-archlinux:
        docker_firewall_flavor: "nftables"

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
