---
# Copyright (C) 2021 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 256
      cpus: 2

platforms:
  - name: test-docker-ubuntu2004
    box: generic/ubuntu2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10
  - name: test-docker-ubuntu1804
    box: generic/ubuntu1804
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.20
  - name: test-docker-debian10
    box: generic/debian10
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.30
  - name: test-docker-debian11
    box: generic/debian11
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.40
  - name: test-docker-archlinux
    box: archlinux/archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.50

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
