---
- name: Prepare Ubuntu and Debian hosts
  hosts: ubuntu, debian
  gather_facts: false
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install python3-requests package
      ansible.builtin.package:
        name: "python3-requests"
        state: present

- name: Prepare Archlinux
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: Init pacman
      ansible.builtin.raw: |
        pacman-key --init
        pacman-key --populate archlinux
      changed_when: false
      failed_when: false

    - name: Updating pacman cache
      ansible.builtin.raw: |
        pacman -Sy
      changed_when: false

    - name: Install support packages
      ansible.builtin.raw: |
        pacman -S --noconfirm python openssl archlinux-keyring
      args:
        executable: /bin/bash
      changed_when: false

    - name: Install python3-requests package
      ansible.builtin.package:
        name: "python-requests"
        state: present
