---
- name: Prepare Ubuntu and Debian hosts
  hosts: ubuntu, debian
  gather_facts: false
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install python3-requests package
      ansible.builtin.package:
        name: "python3-requests"
        state: present

- name: Prepare Archlinux
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: Init pacman
      ansible.builtin.raw: |
        pacman-key --init
        pacman-key --populate archlinux
      become: true

    - name: Updating pacman cache
      raw: pacman -Sy
      become: true

    - name: Install Python
      ansible.builtin.raw: |
        pacman -S --noconfirm python
      args:
        executable: /bin/bash
      changed_when: false
      become: true

    - name: Upgrade the whole system
      ansible.builtin.raw: pacman --noconfirm -Su
      become: true

    - name: Install python3-requests package
      ansible.builtin.package:
        name: "python-requests"
        state: present

    - name: Reboot for kernel updates
      ansible.builtin.reboot:
