---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Verify setup
  hosts: all
  tasks:
    - name: Pull image
      community.docker.docker_image:
        name: xperimental/goecho
        tag: v1.8
        source: pull
        pull:
          platform: amd64

    - name: Start container
      community.docker.docker_container:
        name: goecho
        image: xperimental/goecho:v1.8
        state: started
        ports:
          - "8080:8080"

    - name: Check goecho output
      ansible.builtin.uri:
        url: http://localhost:8080
        return_content: true
      register: goecho
      failed_when: "'User-Agent' not in goecho.content"

- name: Verify docker-compose installed
  hosts: test-docker-ubuntu2204
  vars:
    docker_compose_version_output: "Docker Compose version"
  tasks:
    - name: Check docker-compose version output
      ansible.builtin.command:
        cmd: "docker-compose -v"
      register: docker__docker_compose_version
      changed_when: false

    - name: Ensure docker-compose --version output
      ansible.builtin.assert:
        that:
          - "docker_compose_version_output in docker__docker_compose_version.stdout"
